Changed Homeki to use MySQL as database for perfomance reasons. Includes the following changes:  * Replaced hsqldb-2.2.8.jar with a MySQL JDBC client driver connector.  * Modified postinst script to create a MySQL homeki database and user. This requires root password to be 'homeki'.  * Removed archiving of old database on Homeki uninstall (prerm script modified). The MySQL database is left as it is.  * Modified connection strings for Hibernate and Liquibase (hibernate.cfg.xml and DatabaseUpgrader.java).  * Added scripts for manually creating and dropping homeki MySQL database (for development use).  * Stopped using SQL sequences for generating unique IDs (which MySQL does not support, and which is inefficient anyway).  * Made timer trigger use a JOINED table strategy instead of TABLE_PER_SUBCLASS, mostly due to sequences no longer are supported with MySQL.

diff --git a/ant/postinst b/ant/postinst
--- a/ant/postinst
+++ b/ant/postinst
@@ -3,6 +3,12 @@
 set -e
 
 if [ "$1" = "configure" ] ; then
+	DBUSER=root
+	DBPASS=homeki
+	HDBUSER=homeki
+	HDBPASS=homeki
+	START=yes
+
 	echo -n "creating homeki user: "
 	if [ "X`grep "^homeki:" /etc/passwd`" == "X" ]; then
 		useradd --home-dir /home/homeki --create-home --groups admin,plugdev homeki
@@ -10,6 +16,41 @@ if [ "$1" = "configure" ] ; then
 	else
 		echo "not needed, already exists"
 	fi
+	
+	# needed because mysql commands rely on fail exit codes to determine what to do
+	set +e
+	
+	echo -n "connecting to mysql: "
+	echo "exit" | mysql --user=$DBUSER --password=$DBPASS > /dev/null 2>&1
+	
+	if [ $? -ne 0 ]; then
+		echo "connection failed, manual database setup needed"
+		START=no
+	else
+		echo "done"
+	
+		echo -n "creating mysql homeki user: "
+		echo "SELECT User FROM mysql.user WHERE User = 'homeki'" | mysql --user=$DBUSER --password=$DBPASS | grep homeki > /dev/null 2>&1
+		if [ $? -ne 0 ]; then
+			echo "CREATE USER '$HDBUSER'@'localhost' IDENTIFIED BY '$HDBPASS'" | mysql --user=$DBUSER --password=$DBPASS > /dev/null 2>&1
+			echo "done"
+		else
+			echo "not needed, already exists"
+		fi
+	
+		echo -n "creating mysql homeki database: "
+		echo "SHOW DATABASES" | mysql --user=$DBUSER --password=$DBPASS | grep homeki > /dev/null 2>&1
+	        if [ $? -ne 0 ]; then
+	                echo "CREATE DATABASE homeki" | mysql --user=$DBUSER --password=$DBPASS > /dev/null 2>&1
+			echo "done"
+		else
+			echo "not needed, already exists"
+	        fi
+	
+		echo "GRANT ALL ON homeki.* TO 'homeki'@'localhost'" | mysql --user=$DBUSER --password=$DBPASS > /dev/null 2>&1
+	fi
+	
+	set -e
 	
 	echo -n "changing owner of /mnt/1wire: "
 	if [ -d /mnt/1wire ]; then
@@ -25,9 +66,14 @@ if [ "$1" = "configure" ] ; then
 	chmod a+w /opt/homeki/stderr.log
 	echo "done"
 	
+	echo -n "adding S99homeki symlink to runlevel 2: "
 	ln -sf /etc/init.d/homekid /etc/rc2.d/S99homeki
-	echo "------------------- APT: STARTED HOMEKI -------------------" >> /opt/homeki/stdout.log
-	/etc/init.d/homekid start
+	echo "done"
+	
+	if [ $START == "yes" ]; then
+		echo "------------------- APT: STARTED HOMEKI -------------------" >> /opt/homeki/stdout.log
+		/etc/init.d/homekid start
+	fi
 fi
 
 exit 0
